//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeMeuMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificados
    {
        public int IDCertificado { get; set; }
        public string Nome { get; set; }
        public Nullable<long> IDMedico { get; set; }
        public bool Certificado1 { get; set; }
        public bool Certificado2 { get; set; }
        public bool Certificado3 { get; set; }
        public bool Certificado4 { get; set; }
        public bool Certificado5 { get; set; }
        public bool Certificado6 { get; set; }
        public Nullable<int> CargaHoraria { get; set; }
    
        public virtual Medicos Medicos { get; set; }
    }
}
